# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'Final Project' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Final Project
pod 'NAModalSheet'
pod 'SDWebImage'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'SWRevealViewController'
pod 'hpple'
end
